version: '3'
services:
  api:
    build: .
    ports:
     - "8080:8080"
    links:
      - "db"
  db:
    image: "neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/kiwi  